# documentation:
# Environments -> Environment secrets: https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context
# Environments -> Environment variables: https://docs.github.com/actions/learn-github-actions/contexts#vars-context
# Secrets in reusable workflows: https://colinsalmcorner.com/consuming-environment-secrets-in-reusable-workflows/
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      container_name:
        type: string
        description: name for the docker container
        required: true
      tag:
        type: string
        description: tag for the docker image
        required: true

name: Deploy (reusable workflow)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_CERT }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.tag }}
            docker stop ${{ inputs.container_name }} || true
            docker rm ${{ inputs.container_name }} || true
            docker run -i -t -d --restart=always --name=${{ inputs.container_name }} \
              -e PICLIBBOT_PicLibBot__TelegramBotApiKey='${{ secrets.PICLIBBOT_PICLIBBOT__TELEGRAMBOTAPIKEY }}' \
              -e PICLIBBOT_PicLibBot__BraveApiKey='${{ secrets.PICLIBBOT_PICLIBBOT__BRAVEAPIKEY }}' \
              -e PICLIBBOT_PicLibBot__MaxInlineResults='${{ vars.PICLIBBOT_PICLIBBOT__MAXINLINERESULTS }}' \
              ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.tag }}
